# Numpy Part 02

In [1]:
import numpy as np

### 4. Operation

In [3]:
a= np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

* sum 및 axis

In [4]:
# 모든 엘리먼트의 합
a.sum()     

78

In [5]:
# 열의 합
a.sum(axis=0)

array([15, 18, 21, 24])

In [6]:
# 행의 합
a.sum(axis=1)

array([10, 26, 42])

In [8]:
np.sum(a[1])        # 행 인덱스1 : 5,6,7,8의 합 

26

In [9]:
a.min(axis=0)

array([1, 2, 3, 4])

In [10]:
a.max(axis=1)

array([ 4,  8, 12])

In [11]:
a.mean()

6.5

In [13]:
a.mean(axis=0), a.mean(axis=1)

(array([5., 6., 7., 8.]), array([ 2.5,  6.5, 10.5]))

* sorting

In [14]:
b= np.array([[4,3,5,7], [1,12,11,9], [2,5,1,14]])
b

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2,  5,  1, 14]])

In [15]:
# axis = 1, ascending order
np.sort(b)      

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [16]:
np.sort(b, axis=0)

array([[ 1,  3,  1,  7],
       [ 2,  5,  5,  9],
       [ 4, 12, 11, 14]])

In [19]:
b.sort()
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [22]:
b.sort(axis=0)
b

array([[ 1,  2,  5,  7],
       [ 1,  4,  5, 12],
       [ 3,  9, 11, 14]])

In [25]:
# 내림차순 : 별도의 방법이 없음
c= np.array([42,38,12,25])
np.sort(c)

array([12, 25, 38, 42])

In [26]:
# 아래와 같이 내림차순 만들 수 있음
c= np.array([42,38,12,25])
np.sort(c)[::-1]

array([42, 38, 25, 12])

In [28]:
# 가장작은 값 12의 인덱스 2, 두번째 25의 인덱스3, 세번째 38의 인덱스 1, 제일 큰 값 42의 인덱스 0 의미
np.argsort(c)

array([2, 3, 1, 0], dtype=int64)

In [29]:
c[[2,3,1,0]]

array([12, 25, 38, 42])

In [30]:
indices = np.argsort(c)
c[indices]

array([12, 25, 38, 42])

* Mathematical functions

In [31]:
# sigmoid 함수

def sigmoid(x):
    return 1. / (1 + np.exp(-x))

In [32]:
X = np.array([-10,0,10])
sigmoid(X)

array([4.53978687e-05, 5.00000000e-01, 9.99954602e-01])

* Transpose(전치)

In [33]:
b

array([[ 1,  2,  5,  7],
       [ 1,  4,  5, 12],
       [ 3,  9, 11, 14]])

In [35]:
# 행,열 바꿈 
b.T

array([[ 1,  1,  3],
       [ 2,  4,  9],
       [ 5,  5, 11],
       [ 7, 12, 14]])

* concatenate, vstack, hstack

In [37]:
a= np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [39]:
b= np.array([[5,6]])
b

array([[5, 6]])

In [40]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
# vstack과 같음
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
np.hstack((a, b.T))

array([[1, 2, 5],
       [3, 4, 6]])

In [45]:
# hstack과 같음
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

### 5. Array operation

* 4칙연산

In [46]:
a

array([[1, 2],
       [3, 4]])

In [47]:
a+a

array([[2, 4],
       [6, 8]])

In [48]:
a-a

array([[0, 0],
       [0, 0]])

In [49]:
a*a

array([[ 1,  4],
       [ 9, 16]])

In [50]:
a/a

array([[1., 1.],
       [1., 1.]])

* Broadcasting

In [51]:
a+3

array([[4, 5],
       [6, 7]])

* Dot product

In [52]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(3,2)

In [53]:
np.dot(a,b)

array([[ 58,  64],
       [139, 154]])

In [55]:
# 이렇게도 쓸 수 있음
a.dot(b)

array([[ 58,  64],
       [139, 154]])

In [56]:
np.dot(np.array([1,2,3]), np.array([4,5,6]))

32

### 6. Comparison

* all & any

In [58]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [60]:
# 하나라도 True가 있으면 True
np.any(a>5)

True

In [62]:
# 모두가 True이어야 True
np.all(1>5)

False

* Logical operation

In [63]:
b= np.logical_and(a>3, a<7)
b

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [64]:
b= np.logical_or(a>7, a<3)
b

array([ True,  True,  True, False, False, False, False, False,  True,
        True])

* argmax, argmin

In [67]:
a.argmax()      # = np.argmax(a)

9

In [68]:
a.argmin(), np.argmin(a)

(0, 0)

### 7. Boolean & Fancy indexing

* boolean indexing

In [69]:
# array a 에서 값이 6이상인 것만 가져오기 : filtering

a[a>=6]

array([6, 7, 8, 9])

In [70]:
a >= 6

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [71]:
b

array([ True,  True,  True, False, False, False, False, False,  True,
        True])

In [73]:
a[b]

array([0, 1, 2, 8, 9])

* fancy indexing

In [74]:
a= np.array([2,4,6,8])
b= np.array([0,0,1,3,2,1])

a[b]        # b가 인덱스값이 됨

array([2, 2, 4, 8, 6, 4])

### 8. 기술 통계

In [75]:
a= np.random.randn(10)
a

array([ 1.02704944,  1.19324705,  0.4074949 , -1.28193233, -0.61777875,
       -1.16068976, -0.51708459,  2.15805413, -0.39681734,  0.5676787 ])

In [76]:
# 평균
np.mean(a), a.mean()

(0.1379221451178581, 0.1379221451178581)

In [77]:
# 표준편차(standard deviation)
np.std(a), a.std()

(1.0597638902826725, 1.0597638902826725)

In [78]:
# 최소, 최대
a.min(), a.max()

(-1.2819323303620496, 2.15805413424516)

In [79]:
# 4분위수( 최소, 25%1분위수, 50%중앙값, 3분위수75%, 최대값)
np.percentile(a,25), np.percentile(a,50), np.percentile(a,75)


(-0.5926052137232851, 0.005338781413311511, 0.9122067575693524)

In [81]:
# 중앙값
np.median(a)        # = np.percentile(a,50)

0.005338781413311511

In [82]:
# 0에서 3까지 100개 추출
a = np.random.randint(0,3,100)
a

array([0, 0, 1, 1, 1, 1, 0, 2, 1, 0, 2, 0, 1, 0, 1, 2, 0, 1, 0, 0, 2, 2,
       1, 2, 2, 1, 2, 2, 0, 0, 0, 2, 0, 2, 2, 1, 1, 2, 0, 1, 0, 1, 2, 2,
       0, 0, 1, 2, 2, 1, 2, 0, 0, 2, 1, 1, 2, 1, 1, 0, 1, 0, 2, 1, 0, 1,
       1, 0, 1, 2, 2, 0, 0, 0, 1, 1, 2, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 2, 0, 2, 2, 1, 0, 0])

In [83]:
# 위에서 0,1,2의 갯수 ★
np.unique(a, return_counts=True)

(array([0, 1, 2]), array([36, 37, 27], dtype=int64))