<pre>
1. 넘파이를 사용하여 다음과 같은 행렬을 만드시오.
10 20 30 40
50 60 70 80
</pre>

In [2]:
import numpy as np

In [3]:
a=np.array([[10,20,30,40],[50,60,70,80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [5]:
# 강사 문제풀이

np.arange(1,9).reshape(2,4)*10      # = np.arange(10,81,10).reshape(2,4)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

<pre>
2. 다음 행렬과 같은 행렬이 있다.
m = np.array([[ 0, 1, 2, 3, 4],
 [ 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14]])
1) 이 행렬에서 값 7 을 인덱싱한다.
2) 이 행렬에서 값 14 을 인덱싱한다.
3) 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
4) 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
5) 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
</pre>

In [4]:
m= np.array([[ 0, 1, 2, 3, 4], 
 [ 5, 6, 7, 8, 9], 
 [10, 11, 12, 13, 14]])

In [5]:
# 7 인덱싱
m[1,2]

7

In [7]:
# 14인덱싱
m[2,-1], m[-1,-1]

(14, 14)

In [9]:
# [6,7] 슬라이싱
m[1:2,1:3]      

array([[6, 7]])

In [11]:
# [7,12] 슬라이싱
m[1:,2:3]       # = m[1:,2] 2차원

array([[ 7],
       [12]])

In [14]:
# [[3, 4], [8, 9]] 슬라이싱
m[:2,3:5]       

array([[3, 4],
       [8, 9]])

In [8]:
m[:-1, 3:]

array([[3, 4],
       [8, 9]])

In [6]:
# 강사문제풀이

m=np.arange(15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

<pre>
3. 2번의 행렬 m을 1차원 벡터 f 로 변환한 후 다음의 문제를 푸시오.
1) 이 배열에서 3의 배수를 찾아라.
2) 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
3) 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
</pre>

In [52]:
# 1차원 변경
m.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [54]:
# 3의배수
m[m%3==0]

array([ 0,  3,  6,  9, 12])

In [55]:
# 4로 나누면 1이 남는 수
m[m%4==1]

array([ 1,  5,  9, 13])

In [59]:
# 3으로 나누면 나누어지고, 4로 나누면 1이 남는 수
m[(m%3==0) + (m%4==1)]

array([ 0,  1,  3,  5,  6,  9, 12, 13])

In [9]:
# 강사문제풀이
m[np.logical_and(m%3==0, m%4==1)]

array([9])

<pre>
4. 값을 직접 입력하지 말고우측의 행렬을 만드시오.

2, 1, 0, 0, 0
3, 2, 1, 0, 0
0, 3, 2, 1, 0
0, 0, 3, 2, 1
0, 0, 0, 3, 2
</pre>

In [30]:
np.eye(5,5, k=-1, dtype=int)*3 + np.eye(5,5, k=0, dtype=int)*2 + np.eye(5,5, k=1, dtype=int)

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])

In [11]:
# 강사문제풀이
np.eye(5,5, -1, int)*3 + np.eye(5,5,0, int)*2 + np.eye(5,5, 1, int)

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])

<pre>
5. 0에서 10까지 랜덤 실수값으로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에
대해 다음과 같은 값을 구하시오.
1) 전체의 최댓값
2) 각 행의 합
3) 각 행의 최댓값
4) 각 열의 평균
5) 각 열의 최솟값
</pre>

In [15]:
b= np.random.randint(0,11,size=(5,6))
b

array([[10,  5,  0,  7,  5,  5],
       [ 8,  2,  4,  0,  9,  4],
       [ 9,  8,  8,  0,  3,  9],
       [ 5,  2,  1,  7,  2,  1],
       [ 7,  9,  6,  6, 10,  7]])

In [13]:
# 강사문제풀이
np.random.seed(2022)
m=np.random.uniform(0,10,30).reshape(5,6).round(4)
m

array([[0.0936, 4.9906, 1.1338, 0.4997, 6.8541, 4.8699],
       [8.9766, 6.4745, 8.9696, 7.2113, 8.3135, 8.2757],
       [8.3358, 9.5704, 3.6804, 4.9484, 3.3951, 6.1943],
       [9.7753, 0.9643, 7.4421, 2.925 , 2.9868, 7.5247],
       [0.1866, 5.2374, 8.6444, 3.8884, 2.1219, 4.7518]])

In [16]:
# 전체 최대값
b.max()

10

In [45]:
# 각 행의 합
b.sum(axis=1)

array([25, 24, 35, 34, 27])

In [46]:
# 각 행의 최대값
b.max(axis=1)

array([ 8,  9, 10, 10,  8])

In [47]:
# 각 열의 평균
b.mean(axis=0)

array([3.8, 6. , 4.8, 7. , 4.4, 3. ])

In [48]:
# 각 열의 최소값
b.min(axis=0)

array([0, 0, 2, 5, 0, 0])

<pre>
6. 다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은
배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하시오.
array([[ 1, 2, 3, 4],
 [ 46, 99, 100, 71],
 [ 81, 59, 90, 100]])
</pre>


In [18]:
# 강사문제풀이
# pandas로 활용이 더 큼

score = np.array([[ 1, 2, 3, 4],
 [ 46, 99, 100, 71],
 [ 81, 59, 90, 100]])
score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [19]:
# 영어 성적을 argsort()
indices = np.argsort(score[1])      # 1은 행인덱스1 의미
indices

array([0, 3, 1, 2], dtype=int64)

In [20]:
# 내림차순
indices[::-1]

array([2, 1, 3, 0], dtype=int64)

In [21]:
# 모든 행을 영어성적 내림차순 기준으로 정렬
# 앞에는행, 뒤에는 열

score[:, indices[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [22]:
# 한 줄로 표시한다면
score[:, np.argsort(score[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

<pre>
7. 주사위를 100번 던지는 가상 실험을 파이썬으로 작성하고, 
던져서 나오는 숫자의 평균을 구하시오.
</pre>

In [23]:
c= np.random.randint(1,7,size=100)
np.mean(c)

3.45

In [24]:
# dice array에서의 고유값 (dice=c)
np.unique(c)

array([1, 2, 3, 4, 5, 6])

In [25]:
# dice array에서 고유값 및 그 갯수
np.unique(c, return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([18, 12, 20, 20, 17, 13], dtype=int64))

In [26]:
unique, counts = np.unique(c, return_counts=True)
dict(zip(unique, counts))

{1: 18, 2: 12, 3: 20, 4: 20, 5: 17, 6: 13}

<pre>
8. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%
인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하시오.
</pre>

In [27]:
# 강사문제풀이
#5개만 먼저테스트

np.random.seed(2022)
rate = np.random.normal(0,0.01,5)
price=10000
for i in range(5):
    price=np.round(price*(1+rate[i]))
    print(int(price), end=' ')

10000 9973 9959 10157 10186 

In [28]:
# 정규분포, 250개 리스트로 처리하는 방법
np.random.seed(2022)
rate = np.random.normal(0,0.01,250)
price=10000
price_list = []
for i in range(250):
    price=np.round(price*(1+rate[i]))
    price_list.append(price)

price_array= np.array(price_list, dtype=np.int32)
price_array[-10:]

array([10916, 10834, 10753, 10838, 10950, 11089, 11006, 11182, 11360,
       11658])

In [29]:
# 정규분포, 처음부터 어레이로 만들어서 처리하는 방법
np.random.seed(2022)
rate = np.random.normal(0,0.01,250)
price=10000
price_array = np.empty(250, dtype=np.int32)

for i in range(250):
    price=np.round(price*(1+rate[i]))
    price_array[i] = price
    
price_array[-10:]

array([10916, 10834, 10753, 10838, 10950, 11089, 11006, 11182, 11360,
       11658])

In [30]:
# 표준정규분포 randn 사용시
np.random.seed(2022)
rate = np.random.randn(250)
price=10000
price_array = np.empty(250, dtype=np.int32)

for i in range(250):
    price=np.round(price*(1+rate[i]*0.01))
    price_array[i] = price
    
price_array[-10:]

array([10916, 10834, 10753, 10838, 10950, 11089, 11006, 11182, 11360,
       11658])