<pre>
1. 넘파이를 사용하여 다음과 같은 행렬을 만드시오.
10 20 30 40
50 60 70 80
</pre>

In [1]:
import numpy as np

In [2]:
a=np.array([[10,20,30,40],[50,60,70,80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

<pre>
2. 다음 행렬과 같은 행렬이 있다.
m = np.array([[ 0, 1, 2, 3, 4],
 [ 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14]])
1) 이 행렬에서 값 7 을 인덱싱한다.
2) 이 행렬에서 값 14 을 인덱싱한다.
3) 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
4) 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
5) 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
</pre>

In [4]:
m= np.array([[ 0, 1, 2, 3, 4], 
 [ 5, 6, 7, 8, 9], 
 [10, 11, 12, 13, 14]])

In [5]:
# 7 인덱싱
m[1,2]

7

In [6]:
# 14인덱싱
m[2,-1]

14

In [9]:
# [6,7] 슬라이싱
m[1:2,1:3]

array([[6, 7]])

In [11]:
# [7,12] 슬라이싱
m[1:,2:3]

array([[ 7],
       [12]])

In [14]:
# [[3, 4], [8, 9]] 슬라이싱
m[:2,3:5]

array([[3, 4],
       [8, 9]])

<pre>
3. 2번의 행렬 m을 1차원 벡터 f 로 변환한 후 다음의 문제를 푸시오.
1) 이 배열에서 3의 배수를 찾아라.
2) 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
3) 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
</pre>

In [52]:
# 1차원 변경
m.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [54]:
# 3의배수
m[m%3==0]

array([ 0,  3,  6,  9, 12])

In [55]:
# 4로 나누면 1이 남는 수
m[m%4==1]

array([ 1,  5,  9, 13])

In [59]:
# 3으로 나누면 나누어지고, 4로 나누면 1이 남는 수
m[(m%3==0) + (m%4==1)]

array([ 0,  1,  3,  5,  6,  9, 12, 13])

<pre>
4. 값을 직접 입력하지 말고우측의 행렬을 만드시오.

2, 1, 0, 0, 0
3, 2, 1, 0, 0
0, 3, 2, 1, 0
0, 0, 3, 2, 1
0, 0, 0, 3, 2
</pre>

In [30]:
np.eye(5,5, k=-1, dtype=int)*3 + np.eye(5,5, k=0, dtype=int)*2 + np.eye(5,5, k=1, dtype=int)

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])

<pre>
5. 0에서 10까지 랜덤 실수값으로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에
대해 다음과 같은 값을 구하시오.
1) 전체의 최댓값
2) 각 행의 합
3) 각 행의 최댓값
4) 각 열의 평균
5) 각 열의 최솟값
</pre>

In [43]:
b= np.random.randint(0,11,size=(5,6))
b

array([[ 0,  4,  8,  5,  6,  2],
       [ 4,  9,  2,  7,  2,  0],
       [ 1,  9,  5,  8, 10,  2],
       [ 8,  0,  6, 10,  4,  6],
       [ 6,  8,  3,  5,  0,  5]])

In [45]:
# 각 행의 합
b.sum(axis=1)

array([25, 24, 35, 34, 27])

In [46]:
# 각 행의 최대값
b.max(axis=1)

array([ 8,  9, 10, 10,  8])

In [47]:
# 각 열의 평균
b.mean(axis=0)

array([3.8, 6. , 4.8, 7. , 4.4, 3. ])

In [48]:
# 각 열의 최소값
b.min(axis=0)

array([0, 0, 2, 5, 0, 0])

<pre>
6. 다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은
배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하시오.
array([[ 1, 2, 3, 4],
 [ 46, 99, 100, 71],
 [ 81, 59, 90, 100]])
</pre>


In [76]:
a=([[ 1, 2, 3, 4],
 [ 46, 99, 100, 71],
 [ 81, 59, 90, 100]])

np.array(a)
np.argsort(a[1],axis=0)


array([0, 3, 1, 2], dtype=int64)

<pre>
7. 주사위를 100번 던지는 가상 실험을 파이썬으로 작성하고, 
던져서 나오는 숫자의 평균을 구하시오.
</pre>

In [51]:
c= np.random.randint(1,7,size=100)
np.mean(c)

3.33

<pre>
8. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%
인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하시오.
</pre>

In [50]:
np.random.normal(10000,1,250)

array([10000.69507608, 10001.03338841,  9999.9784572 , 10000.14961287,
       10001.11006614,  9998.93067353, 10001.15735803, 10000.3246939 ,
        9998.56717399, 10000.53634052,  9998.90128783,  9997.71047993,
        9999.22242379, 10000.2073799 ,  9998.47397994,  9999.51154268,
       10001.4142608 , 10001.35290706, 10001.67602984, 10000.96451862,
       10002.10931446, 10000.4080327 , 10000.46772459,  9999.84033195,
        9999.63124794, 10001.00178741,  9998.95384636,  9999.45336827,
       10000.70539213, 10000.29739256, 10000.15681775,  9999.71450501,
        9999.14289825, 10001.48025785, 10000.59702906,  9999.66559506,
        9999.25672769,  9998.79342774, 10000.06330307,  9998.3408492 ,
        9999.1970091 , 10001.35360396,  9998.90818197, 10000.46858485,
       10001.74537297,  9999.84796347, 10000.29457387, 10000.57237616,
        9999.98276153, 10000.80193986,  9997.4018492 ,  9998.26192244,
       10000.90838108, 10000.36071237,  9999.63743185, 10000.55636687,
      